import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import CommonFooter from '../shared_components/CommonFooter'
import TopTracks from '../shared_components/spotify/TopTracks'
import NowPlaying from '../shared_components/spotify/NowPlaying'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Liam Pulsifer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Liam Pulsifer
        </h1>

        <div className={styles.grid}>
          
        </div>
        <TopTracks/>
        <NowPlaying />
      </main>

      <CommonFooter />
    </div>
  )
}
